export const CREATE_USER= 'CREATE_USER'
export const RECIEVED_NEW_USER = 'RECIEVED_NEW_USER'
export const FAILURE_CREATE_USER = 'FAILURE_CREATE_USER'

export const LOGIN_ADMIN = "LOGIN_ADMIN"
export const SUCCESS_LOGIN_ADMIN = 'SUCCESS_LOGIN_ADMIN'
export const FAILURE_LOGIN_ADMIN = 'FAILURE_LOGIN_ADMIN'

export const GET_ALL_USERS = "GET_ALL_USERS"
export const SUCCESS_GET_ALL_USERS = 'SUCCESS_GET_ALL_USERS'
export const FAILURE_GET_ALL_USERS= 'FAILURE_GET_ALL_USERS'


export const ADD_MESSAGES= 'ADD_MESSAGES'
export const RECIEVED_ADD_MESSAGES= 'RECIEVED_ADD_MESSAGES'
export const FAILURE_ADD_MESSAGES = 'FAILURE_ADD_MESSAGES'

export const GET_MESSAGES = "GET_MESSAGES"
export const SUCCESS_GET_MESSAGES = "SUCCESS_GET_MESSAGES"
export const FAILURE_GET_MESSAGES = "FAILURE_GET_MESSAGES"

export const GET_MESSAGES_ROOM = "GET_MESSAGES_ROOM"
export const SUCCESS_GET_MESSAGES_ROOM = "SUCCESS_GET_MESSAGES_ROOM"
export const FAILURE_GET_MESSAGES_ROOM = "FAILURE_GET_MESSAGES_ROOM"

export const GET_USER = "GET_USER"
export const SUCCESS_GET_USER = 'SUCCESS_GET_USER'
export const FAILURE_GET_USER= 'FAILURE_GET_USER'